server:
    port: 8091
spring:
    application:
        name: gateway-spring-cloud
    cloud:
        gateway:
            routes:
                - id: producerId
                  uri: http://localhost:8082/
                  predicates:
                      - Path=/producer/**
                - id: consumerId
                  uri: http://localhost:8083/
                  predicates:
                      - Path=/consumer/**
    main:
        allow-bean-definition-overriding: true
